import {
    ElForm,
    ElFormItem,
    ElRow,
    ElCol,
    ElInput,
    ElInputNumber,
    ElDialog,
    ElSelect,
    ElOption,
    ElOptionGroup,
    ElMessageBox,
    ElMessage,
    ElCheckboxGroup,
    ElCheckboxButton,
    ElCheckbox,
    ElLoading,
    ElConfigProvider,
    ElAutocomplete,
    ElNotification,
    ElRadioGroup,
    ElRadio,
    ElPopover,
    ElDrawer,
    ElSlider,
    ElRate,
    ElSkeleton
} from "element-plus";

const ElPlus = {
    ElForm,
    ElDrawer,
    ElFormItem,
    ElRow,
    ElCol,
    ElInput,
    ElInputNumber,
    ElDialog,
    ElSelect,
    ElOption,
    ElOptionGroup,
    ElMessageBox,
    ElMessage,
    ElCheckboxGroup,
    ElCheckboxButton,
    ElCheckbox,
    ElLoading,
    ElConfigProvider,
    ElAutocomplete,
    ElNotification,
    ElRadioGroup,
    ElRadio,
    ElPopover,
    ElSlider,
    ElRate,
    ElSkeleton
}

export default ElPlus;